/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Business.CSO;

/**
 *
 * @author yashrevadekar
 */
public class CSO {
   private String Name;
    private String csoid;
    private static int count;
    //CSO constructor to autogenerated ids
    public CSO() {
        
        csoid="ORG"+(++count);
        
    }
    
    public String getNgoid() {
        return csoid;
    }

    public void setNgoid(String ngoid) {
        this.csoid = ngoid;
    }
    
    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }
    
    @Override
    public String toString(){
        
        return Name;
    } 
}
